[package]
name = "technical_analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ta = "0.5.0"
rust_decimal = "1.15"
rust_decimal_macros = "1.15"
